name: sapiens-fixed
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - cudatoolkit=11.7
  - numpy=1.25.2
  - matplotlib=3.7.3
  - pip
  - pip:
    - mmdet==3.3.0
    - mmcv==2.0.1
    - mmengine==0.10.7
    - opencv-python-headless>=4.9.0
    - pycocotools
    - scipy
    - shapely
    - terminaltables
    - tqdm 